### ISSUE TITLE
When will PWA be available?

### ISSUE THREAD

**Issue by andrewmunro** [MartinBlackburn/blackburn.dev#2]
Nice website! I wanted to ask if a [PWA](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps) is in the works? I'd love the opportunity to add this to my homescreen so I can keep up to date with the latest blackburn news!

![blackburn-pwa](https://github.com/MartinBlackburn/blackburn.dev/assets/1107388/3f146e70-fc43-45c1-a7e7-1297f3363ba3)

**Comment by MartinBlackburn** [comment]
no
